// <auto-generated />
using System;
using Cheers.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cheers.DB.Migrations
{
    [DbContext(typeof(CheersDbContext))]
    [Migration("20190610094857_updated CheerTable Schema")]
    partial class updatedCheerTableSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cheers.DB.Models.CheerTable", b =>
                {
                    b.Property<int>("CheerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheerFrom");

                    b.Property<string>("CheerText");

                    b.Property<DateTime>("CheerTime");

                    b.Property<string>("CheerTo");

                    b.HasKey("CheerID");

                    b.HasIndex("CheerFrom");

                    b.HasIndex("CheerTo");

                    b.ToTable("CheerTable");
                });

            modelBuilder.Entity("Cheers.DB.Models.User", b =>
                {
                    b.Property<string>("UPN")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("FullName");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName");

                    b.Property<string>("UserGUID");

                    b.HasKey("UPN");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cheers.DB.Models.CheerTable", b =>
                {
                    b.HasOne("Cheers.DB.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("CheerFrom");

                    b.HasOne("Cheers.DB.Models.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("CheerTo");
                });
#pragma warning restore 612, 618
        }
    }
}
